Editor merge
AnarCom/game-engine pull request #7
Opened 2022-12-14 07:58 UTC by anast3t

2022-12-14 08:30 UTC, AnarCom reviewed
про файл empty.png -- такой кажется уже есть в ресурсах -- советую чекнуть main (я для движка делал такой)

2022-12-14 08:30 UTC, AnarCom commented on common/src/main/kotlin/ru/nsu/lib/common/TowerData.kt
> -    val updates:Array<TowerUpdate>
Теперь сюда можно так же вернуть array, поскольку длина теперь тебе известна в момент сериализации

2022-12-14 08:30 UTC, AnarCom commented on editor/build.gradle.kts
> +//    implementation("no.tornado:tornadofx:1.7.20")
Коммент бы убрать....

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/TowerEditorView.kt
> +                else -> {
Ты уверен, кто код может попасть в это условие?

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/TowerEditorView.kt
> +                    Files.createDirectories(Paths.get(jsonFolder, "/${menuValue.value}/"))
Движок всегда читает из папки configurations (или в каком там оно числе), менять это удобным способом не получится

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/TowerEditorView.kt
> +//                    println(Paths.get(jsonFolder, "/$menuValue/test.json").toFile())
коммент бы убрать...

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/TowerEditorView.kt
> +}
Пустая строка в конце файла (так просто принято делать в git, поскольку это система контроля версий из linux, а там пустая строка в конце из определения файла следует)

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/EnemySettingsComponent.kt
> +        } catch(e : NumberFormatException){
возможно (если будет время), стоит впилить валидацию на input (или чекнуть нет ли там прям текстовых полей)

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/EnemySettingsComponent.kt
> +        return EnemyType(0,0,"./",0)
выбрось ошибку наружу, чтобы ты просто остановил процесс сериализации и мог вывести там "универсальное" сообщение об ошибке. Тип "если невалидные данные, то и не превратим мы это в json" (+ поможет анотация @throws, но что именно она делает - я не помню :)

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/EnemySettingsComponent.kt
> +}
пустая строка

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/SettingsComponent.kt
> +}
пустая строка

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerSettingsComponent.kt
> +//    override val titleProperty: StringProperty = SimpleStringProperty("TowerSettingsComponent")
к черту ненужные комменты!

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerSettingsComponent.kt
> +                    hboxConstraints {
тут я не разбирался, но мб просто обернуть кнопку в hbox, а не делать ей вложенного родителя? (хотя мб это единтсвенный варик, так что ничего особо говорить не буду)

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerSettingsComponent.kt
> +}
пустая строка

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerUpgradeComponent.kt
> +//    override val titleProperty: StringProperty = SimpleStringProperty("TowerSettingsComponent")
комменты

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerUpgradeComponent.kt
> +        } catch(e : NumberFormatException){
тоже самое, про исключение и отказ возвращать данные

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerUpgradeComponent.kt
> +//                                    if(towerData.updates[index]) TODO: towertype == AOE -> add field aoe radius || else - max attack enemies
//

2022-12-14 08:30 UTC, AnarCom commented on editor/src/main/resources/index.css
> +}
пустая строка

2022-12-20 12:16 UTC, anast3t commented on editor/src/main/kotlin/ru/nsu/editor/view/component/EnemySettingsComponent.kt
> +        } catch(e : NumberFormatException){
я пробовал, там головной боли дай боже

2022-12-20 12:24 UTC, AnarCom requested changes

2022-12-20 12:24 UTC, AnarCom commented on editor/src/main/kotlin/ru/nsu/editor/view/component/TowerUpgradeComponent.kt
> -
если это больше не нужно, то это надо удалить, а не закоментить :)

2022-12-20 13:28 UTC, merged